// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250926145042_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Futbol"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Basketbol"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Voleybol"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Price = 4249m,
                            ProductName = "Fenerbahçe 2025/26 Lacivert Forma"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Price = 4249m,
                            ProductName = "Fenerbahçe 2025/26 Çubuklu Forma"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Price = 4249m,
                            ProductName = "Fenerbahçe 2025/26 Sarı Forma"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Price = 3799m,
                            ProductName = "Fenerbahçe Beko 2025/26 Adidas Erkek Çubuklu Forma"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Price = 2499m,
                            ProductName = "Fenerbahçe Beko 2025/26 Adidas Lacivert Erkek Maç Şortu"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Price = 1499m,
                            ProductName = "Fenerbahçe Medicana 24/25 Çubuklu Kadın Voleybol Forma"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
